export const AdditionalBenefits = [
    "Performance-based bonuses",
    "Annual salary reviews",
    "Equity / ESOPs",
    "Joining bonus",
    "Retention bonus",
    "Referral bonuses",
    "Overtime pay",
    "Internet reimbursement",
    "Mobile / phone allowance",

    "Flexible working hours",
    "Remote work option",
    "Hybrid work model",
    "Work-from-anywhere policy",
    "Compressed work weeks",
    "No strict clock-in policy",

    "Health insurance (self + dependents)",
    "Mental health support",
    "Annual health check-ups",
    "Wellness programs",
    "Gym / fitness membership",
    "Paid sick leave",
    "Health & wellness allowance",

    "Paid time off (PTO)",
    "Casual leaves",
    "Sick leaves",
    "Paid parental leave",
    "Maternity leave",
    "Paternity leave",
    "Sabbatical options",
    "Birthday leave",

    "Learning & development budget",
    "Certification reimbursements",
    "Conference / workshop sponsorship",
    "Mentorship programs",
    "Career progression plans",
    "Internal mobility opportunities",

    "Modern office infrastructure",
    "Free meals / snacks",
    "Company-sponsored outings",
    "Team events & offsites",
    "Comfortable workspaces",
    "Recreational zones",

    "Inclusive work environment",
    "Equal opportunity employer",
    "Diversity hiring programs",
    "Women return-to-work programs",
    "LGBTQ+ friendly workplace",

    "Company-provided laptop",
    "Home office setup allowance",
    "Latest tools & software",
    "Ergonomic chair / desk",

    "Relocation assistance",
    "Visa sponsorship",
    "Employee discounts",
    "Childcare support",
    "Pet-friendly office",
    "Company merchandise"
];
