export const educationalRequirements = [
    "Currently pursuing Bachelor's degree",
    "Currently pursuing Master's degree",
    "Currently pursuing Diploma",
    "Recently graduated",
    "Final year student",
    "Undergraduate student",
    "Postgraduate student",
    "PhD scholar",
    "Any graduate",
    "Any undergraduate",
    "2026 passouts only",
    "2025/2026/2027/2028 batch only",
    "Bachelor's in Computer Science",
    "Bachelor's in Information Technology",
    "Bachelor's in Software Engineering",
    "Bachelor's in Data Science",
    "Bachelor's in Artificial Intelligence",
    "Bachelor's in Electronics",
    "Bachelor's in Electrical Engineering",
    "Bachelor's in Mechanical Engineering",
    "Bachelor's in Civil Engineering",
    "Bachelor's in Biotechnology",

    "Master's in Computer Science",
    "Master's in Data Science",
    "Master's in Artificial Intelligence",
    "Master's in Information Technology",
    "Master's in Business Administration (MBA)",

    "BCA",
    "MCA",
    "B.Tech",
    "M.Tech",
    "B.Sc",
    "M.Sc",
    "B.Com",
    "M.Com",
    "BA",
    "MA",
    "BBA",
    "MBA",

    "Engineering student",
    "Science student",
    "Commerce student",
    "Arts student",

    "Students from any discipline",
    "Students from technical background",
    "Students from non-technical background",

    "Minimum 10+2 qualification",
    "Equivalent professional qualification",
    "Relevant educational background",

    "Strong academic record preferred",
    "No strict educational requirement",
    "Education requirement flexible"
];
