import { z } from "zod";

// --- Seeker Profile Schema ---
export const SeekerProfileSchema = z.object({
    name: z.string().min(3, "Name is required").max(100).optional(),
    phone: z.string().min(10, "Phone number must be 10 digits").max(10).optional().nullable(),
    college: z.string().max(200).optional().nullable(),
    course: z.string().max(200).optional().nullable(),
    dob: z.string().max(20).optional().nullable(),
    gender: z.string().max(20).optional().nullable(),
    address: z.string().max(500).optional().nullable(),
    preferred_job_type: z.string().max(50).optional().nullable(),
    availability: z.string().max(50).optional().nullable(),
    preferred_location: z.string().max(50).optional().nullable(),
    degree: z.string().max(50).optional().nullable(),
    college_edu: z.string().max(200).optional().nullable(),
    college_grade: z.string().max(50).optional().nullable(),
    education_duration_start: z.string().max(10).optional().nullable(),
    education_duration_end: z.string().max(10).optional().nullable(),
    class_xii: z.string().max(100).optional().nullable(),
    class_xii_board: z.string().max(100).optional().nullable(),
    class_xii_grade: z.string().max(50).optional().nullable(),
    class_xii_details_start: z.string().max(10).optional().nullable(),
    class_xii_details_end: z.string().max(10).optional().nullable(),
    class_x: z.string().max(100).optional().nullable(),
    class_x_board: z.string().max(100).optional().nullable(),
    class_x_grade: z.string().max(50).optional().nullable(),
    class_x_details_start: z.string().max(10).optional().nullable(),
    class_x_details_end: z.string().max(10).optional().nullable(),
    skills: z.array(z.string()).optional(),
    language_1_name: z.string().max(100).optional().nullable(),
    language_1_proficiency: z.string().max(100).optional().nullable(),
    language_2_name: z.string().max(100).optional().nullable(),
    language_2_proficiency: z.string().max(100).optional().nullable(),
    profile_summary: z.string().max(2000).optional().nullable(),
    awards: z.string().max(1000).optional().nullable(),
    clubs: z.string().max(1000).optional().nullable(),
    // Arrays for complex fields
    internships: z.array(z.any()).optional(),
    projects: z.array(z.any()).optional(),
    certifications: z.array(z.any()).optional(),
    exams: z.array(z.any()).optional(),
    resume_path: z.string().optional().nullable(),
    updated_at: z.date().optional(),
});

// --- Recruiter Profile Schema ---
export const RecruiterProfileSchema = z.object({
    recruiter_name: z.string().min(1, "Name is required").max(100),
    email: z.string().email("Invalid email").max(100).optional(),
    contact_number: z.string().min(10, "Phone number must be 10 digits").max(10).optional().nullable(),
    address: z.string().max(500).optional().nullable(),
    designation: z.string().max(100).optional().nullable(),
    organisation_name: z.string().max(200).optional().nullable(),
    website: z.string().optional().nullable(),
    company_domain: z.string().max(100).optional().nullable(),
    hiring_for: z.string().max(500).optional().nullable(),
});

// --- Job Posting Schema ---
export const JobPostingSchema = z.object({
    id: z.string().optional(),
    company_name: z.string().min(1, "Company name is required").max(200).optional(),
    job_title: z.string().min(1, "Job title is required").max(200).optional(),
    work_experience_min: z.union([z.string(), z.number(), z.bigint()]).optional(),
    work_experience_max: z.union([z.string(), z.number(), z.bigint()]).optional(),
    salary_per_month_from: z.union([z.string(), z.number(), z.bigint()]).optional(),
    salary_per_month_to: z.union([z.string(), z.number(), z.bigint()]).optional(),
    additional_benefits: z.string().optional().nullable(),
    primary_skills: z.string().optional().nullable(),
    employment_type: z.string().optional().nullable(),
    location: z.string().optional().nullable(),
    job_description: z.string().optional().nullable(),
    application_deadline: z.string().optional().nullable(),
    number_of_applications: z.union([z.string(), z.number(), z.bigint()]).optional(),
    educational_requirements: z.string().optional().nullable(),
    communication_preferences: z.string().optional().nullable(),
    key_responsibilities: z.string().optional().nullable(),
    good_to_have: z.string().optional().nullable(),
    what_we_offer: z.string().optional().nullable(),
    company_description: z.string().optional().nullable(),
    website_link: z.string().optional().nullable(),
    company_logo: z.string().optional().nullable(),
    why_join: z.string().optional().nullable(),
    required_qualifications: z.string().optional().nullable(),
    preferred_qualifications: z.string().optional().nullable(),
    recruiter_profile_id: z.union([z.string(), z.number(), z.bigint()]).optional().nullable(),
    draft: z.boolean().optional(),
    created_at: z.string().optional(),
    selection_process: z.string().optional().nullable(),
    skill_description: z.string().optional().nullable(),
    role: z.string().optional().nullable(),
    job_form_link: z.string().optional().nullable(),
    screening_questions: z.array(z.object({
        question: z.string(),
        type: z.string(),
    })).optional(),
});
